# Generated by Django 4.2.5 on 2023-12-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_purpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
